### ISSUE TITLE
What to modify for multi-label classification? 

### ISSUE THREAD

**Issue by ywang530** [ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico#1]
Hi, I just want to reach out to ask what to modify in the `MLModel::predict()` function if I plan to do some multi-label classification. 
Particularly, I think I need to change these two lines of code in the ml_model.cpp.
```
float y_quantized = _output_tensor->data.int8[0];
float y = (y_quantized - _output_tensor->params.zero_point) * _output_tensor->params.scale;
```
The model I intend to use will output 4 numbers for the label probability (4 labels classification).
I wonder how could I modify `_output_tensor->data` to get the 4 numbers.

**Comment by sandeepmistry** [comment]
Hi @ywang530,

I believe you can just loop through the `_output_tensor->data.int8` array for the number of outputs your model has. For example a model with four outputs:

```
float y0 = ((float)_output_tensor->data.int8[0] - _output_tensor->params.zero_point) * _output_tensor->params.scale;
float y1 = ((float)_output_tensor->data.int8[1] - _output_tensor->params.zero_point) * _output_tensor->params.scale;
float y2 = ((float)_output_tensor->data.int8[2] - _output_tensor->params.zero_point) * _output_tensor->params.scale;
float y3 = ((float)_output_tensor->data.int8[3] - _output_tensor->params.zero_point) * _output_tensor->params.scale;
```

**Comment by rohanali1798** [comment]
> Hi, I just want to reach out to ask what to modify in the `MLModel::predict()` function if I plan to do some multi-label classification. Particularly, I think I need to change these two lines of code in the ml_model.cpp.
> 
> ```
> float y_quantized = _output_tensor->data.int8[0];
> float y = (y_quantized - _output_tensor->params.zero_point) * _output_tensor->params.scale;
> ```
> 
> The model I intend to use will output 4 numbers for the label probability (4 labels classification). I wonder how could I modify `_output_tensor->data` to get the 4 numbers.

Hello @ywang530 can you please guide me what changes I need to do on Colab Notebook to make it work for multi-classification?
