### ISSUE TITLE
Can I use this approach to detect a certain set of spoken words?

### ISSUE THREAD

**Issue by maacpiash** [ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico#13]
Greetings!

I am trying to make an IoT device setup with a Raspberry Pi Pico and an Adafruit PDM MEMS Microphone Breakout. My goal is to detect some certain keywords in speech in real time. I have the data from the [Speech Commands Dataset](https://www.tensorflow.org/datasets/catalog/speech_commands). Can I use this dataset and follow this Notebook make it detect keywords? If so, please give me some basic hints regarding where to change the code.

Thanks in advance 🙂

**Comment by sandeepmistry** [comment]
Hi @maacpiash,

That would be possible, but I think the original TF Lite example would be a better fit, as it does some more speech specific pre-processing:
- https://github.com/raspberrypi/pico-tflmicro/tree/main/examples/micro_speech
- https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/micro_speech#micro-speech-example
- https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/micro_speech/train
