### ISSUE TITLE
Fantastic Project!

### ISSUE THREAD

**Issue by gamename** [ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico#14]
Hi Sandeep,

I'm really impressed by this project and the article you wrote about it. Its exactly what I've been looking for.  I hope to leverage it to update my [cat doorbell](https://github.com/gamename/raspberry-pi-iot-cat-doorbell).  I do have a couple questions, though.  

1. In the "Load wive file data" section, there is a dog barking example loaded.  Is that necessary for the project? I'm not sure why its there, tbh. :)
2. In the "Download datasets" section, I'm not sure what this construct for github means:
`'https://github.com/ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico/archive/refs/heads/fire_alarms.tar.gz',`
Did you add the tar file to github, delete it, then refer to it based on the archive?  Never seen this construct before.  Could you explain how that was done?

Thank you, sir.

**Comment by sandeepmistry** [comment]
Hi @gamename,

Thanks for the positive feedback!

> In the "Load wive file data" section, there is a dog barking example loaded. Is that necessary for the project? I'm not sure why its there, tbh. :)

It was there to demonstrate how to load a wave file, and is used to train a broader baseline model, along with other data from the ESC-50k dataset.

> In the "Download datasets" section, I'm not sure what this construct for github means:
'https://github.com/ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico/archive/refs/heads/fire_alarms.tar.gz',
Did you add the tar file to github, delete it, then refer to it based on the archive? Never seen this construct before. Could you explain how that was done?

The files are in the `fire_alarms` branch of this repo, that url is a way to download the items of that branch without using `git`.

You can see the branch here: https://github.com/ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico/tree/fire_alarms

**Comment by gamename** [comment]
Thank you, sir. I may have more questions as I progress in my project.  

Thanks again,
-T
