### ISSUE TITLE
MAX9814 microphone module support

### ISSUE THREAD

**Issue by rohanali1798** [ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico#2]
Hi there!
Great work! I would like to know that if I use Max9814 microphone module with Pico instead of MEMS microphone then what changes should be done in the code?

**Comment by sandeepmistry** [comment]
Hi @rohanali1798,

This is out of scope for this project. However, you can compare the following examples from the [microphone-library-for-pico](https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico) to see the changes that would be required:
* https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico/tree/main/examples/hello_pdm_microphone
* https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico/tree/main/examples/hello_analog_microphone
