### ISSUE TITLE
Inference not running with MAX9814

### ISSUE THREAD

**Issue by Pypico** [ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico#7]
Hi @sandeepmistry,
Great work!
I am facing an issue.
 I ran the colab notebook, it compiled and also created the inference etc. However, when I upload it to pico it does not detect anything and shows "not detected" even though I am only using the test audio.
For clarity, I am using MAX9814 Analog microphone with Raspberry pi pico on pin 26. I tried it a few months back and it was working fine then, but now it does not detect anything. Can you please help with this? 
Thanks.
![serial_output](https://user-images.githubusercontent.com/115140030/194277579-fe6e19fc-0d94-44d8-9273-ba01956a20b6.PNG)

**Comment by sandeepmistry** [comment]
Hi @Pypico,

Are you using an unmodified version of the [interference-app](https://github.com/ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico/tree/main/inference-app)?

If so, the application is built for use with a PDM microphone, expected pin out is:  https://github.com/ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico/blob/main/inference-app/src/main.cpp#L30-L48

**Comment by Pypico** [comment]
Yes, I'm using the unmodified version but it worked earlier with the MAX9814. 
 Anyways, if I were to modify it for the MAX9814, can you shed some light on how to go for it?
I have interfaced the analog mic with pico using your library [microphone-library-for-pico](https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico) and it's giving values on the serial monitor. I am storing it in a buffer as you did in the inference-app and now trying to pass it to the dsp pipeline which is a bit difficult because of a lot of different function parameters.

Thanks again.
