### ISSUE TITLE
Training with your own audio with MAX9814 and Pico Wireless

### ISSUE THREAD

**Issue by ferrygun** [ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico#8]
I followed your instruction on the [Colab](https://colab.research.google.com/github/ArmDeveloperEcosystem/ml-audio-classifier-example-for-pico/blob/main/ml_audio_classifier_example_for_pico.ipynb). How can I train with my own audio with MAX9814?
and how can I use the USB feature with Pico Wireless ?

**Comment by sandeepmistry** [comment]
Hi @ferrygun,

You would need to replace the `pdm_microphone_*` API calls in https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico/blob/main/examples/usb_microphone/main.c with the equivalent `analog_microphone_*` calls from [the microphone-library-for-pico's `analog_microphone.h`](https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico/blob/main/src/include/pico/analog_microphone.h)
